services:
  mysql:
    image: mysql:8.0
    container_name: jaeshop-mysql-dev
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - jaeshop-mysql-data-dev:/var/lib/mysql
    networks:
      - jaeshop-net-dev
    command: >
      mysqld --default-authentication-plugin=caching_sha2_password
             --character-set-server=utf8mb4
             --collation-server=utf8mb4_unicode_ci

volumes:
  jaeshop-mysql-data-dev:

networks:
  jaeshop-net-dev:

